export const categories = {
    "ghe-nha-khoa": {
      slug: "ghe-nha-khoa",
      name: "Ghế Nha Khoa",
      name_en: "Dental Chairs",
      banner: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/9d44d492a_generated_28f20030.png",
      description: "Ghế nha khoa cao cấp nhập khẩu chính hãng, đa dạng mẫu mã từ các thương hiệu hàng đầu thế giới.",
    },
    "den-tram": {
      slug: "den-tram",
      name: "Đèn Trám - Đèn Tẩy Trắng",
      name_en: "Curing & Whitening Lights",
      banner: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/6b1b734a3_generated_6271cc37.png",
      description: "Đèn trám composite và đèn tẩy trắng răng chuyên dụng, công nghệ LED hiện đại, hiệu quả cao.",
    },
    "chan-doan": {
      slug: "chan-doan",
      name: "Thiết Bị Chẩn Đoán Hình Ảnh",
      name_en: "Diagnostic Imaging",
      banner: "/images/cutouts/xray-cbct-cs9300.png",
      description: "Máy chụp X-quang, cảm biến RVG và thiết bị chẩn đoán hình ảnh kỹ thuật số tiên tiến.",
    },
  };
  
  export const products = [
    // --- GHẾ NHA KHOA ---
    {
      id: "ghe-grace-x2",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Grace X2",
      brand: "Grace",
      price: 45000000,
      oldPrice: 52000000,
      image: "/images/cutouts/ghe-grace-x2.png",
      images: [
        "/images/cutouts/ghe-grace-x2.png",
        "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/86b55d54c_generated_image.png",
      ],
      colors: ["#FFFFFF", "#C0C0C0", "#1A1A1A"],
      colorNames: ["Trắng", "Bạc", "Đen"],
      rating: 4.9, reviews: 128,
<<<<<<< HEAD
      tag: "Bán chạy",
=======
      tag: "Best Seller",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Điện áp: 220V/50Hz", "Tải trọng tối đa: 180kg", "Độ cao điều chỉnh: 40-75cm", "Tích hợp đèn LED", "Điều khiển chân không dây"],
      description: "Ghế nha khoa Grace X2 là sản phẩm cao cấp với thiết kế hiện đại, tích hợp đầy đủ các tính năng tiện lợi cho bác sĩ và bệnh nhân. Cơ cấu điều chỉnh êm ái, bọc da cao cấp kháng khuẩn, dễ vệ sinh.",
      inStock: true,
    },
    {
      id: "ghe-suntem-302",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Suntem ST-D302 New",
      brand: "Suntem",
      price: 38000000,
      oldPrice: null,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/782ab061d_generated_image.png",
      images: [
        "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/782ab061d_generated_image.png",
        "/images/cutouts/ghe-grace-x2.png",
      ],
      colors: ["#FFFFFF", "#F5F0E8", "#4A90D9"],
      colorNames: ["Trắng", "Kem", "Xanh"],
      rating: 4.7, reviews: 89,
      tag: "Mới",
      specs: ["Điện áp: 220V/50Hz", "Tải trọng: 160kg", "Bơm nước tích hợp", "Bàn đạp điều khiển", "Đèn khám LED"],
      description: "Suntem ST-D302 New là phiên bản nâng cấp với nhiều cải tiến về thiết kế và tính năng. Đặc biệt phù hợp cho các phòng khám vừa và nhỏ với mức giá hợp lý, chất lượng Hàn Quốc.",
      inStock: true,
    },
    {
      id: "ghe-anthos-a3",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Anthos A3 Plus",
      brand: "Anthos",
      price: 95000000,
      oldPrice: 110000000,
      image: "/images/cutouts/ghe-anthos-a3.png",
      images: [
        "/images/cutouts/ghe-anthos-a3.png",
        "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/782ab061d_generated_image.png",
      ],
      colors: ["#FFFFFF", "#E8E0D5", "#2C3E50"],
      colorNames: ["Trắng", "Kem sang", "Xám đậm"],
      rating: 5.0, reviews: 45,
<<<<<<< HEAD
      tag: "Cao cấp",
=======
      tag: "Premium",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Made in Italy", "Tải trọng: 200kg", "Điều khiển cảm ứng", "Bộ nhớ 5 vị trí", "Hệ thống nước tự động"],
      description: "Anthos A3 Plus là đỉnh cao của kỹ thuật Italy, thiết kế sang trọng với vật liệu cao cấp. Hệ thống điều khiển thông minh, lưu nhớ vị trí cá nhân hóa cho từng bác sĩ. Tiêu chuẩn quốc tế CE.",
      inStock: true,
    },
    {
      id: "ghe-suntem-d307",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Suntem ST-D307",
      brand: "Suntem",
      price: 42000000,
      oldPrice: 48000000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/86b55d54c_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/86b55d54c_generated_image.png"],
      colors: ["#FFFFFF", "#C0C0C0"],
      colorNames: ["Trắng", "Bạc"],
      rating: 4.8, reviews: 62,
<<<<<<< HEAD
      tag: "Giảm giá",
=======
      tag: "Sale",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Điện áp: 220V", "Điều khiển bàn đạp", "Đèn LED chiếu sáng", "Ghế da PU chống khuẩn"],
      description: "Suntem ST-D307 với thiết kế gọn nhẹ, dễ dàng di chuyển. Phù hợp cho không gian phòng khám nhỏ, hiệu quả hoạt động cao.",
      inStock: true,
    },
    {
      id: "ghe-cingol-x3",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Cingol X3 Plus",
      brand: "Cingol",
      price: 55000000,
      oldPrice: null,
      image: "/images/cutouts/ghe-grace-x2.png",
      images: ["/images/cutouts/ghe-grace-x2.png"],
      colors: ["#FFFFFF", "#F5F5DC", "#8B7355"],
      colorNames: ["Trắng", "Be", "Nâu"],
      rating: 4.8, reviews: 37,
<<<<<<< HEAD
      tag: "Nổi bật",
=======
      tag: "Hot",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Xuất xứ Trung Quốc cao cấp", "CE & ISO chứng nhận", "Đèn halogen/LED", "Tay khoan tích hợp"],
      description: "Cingol X3 Plus kết hợp giữa thiết kế hiện đại và tính năng chuyên dụng. Tích hợp đầy đủ module dụng cụ, phù hợp cho phòng khám toàn diện.",
      inStock: false,
    },
    {
      id: "ghe-fengdan-ql2028",
      category: "ghe-nha-khoa",
      name: "Ghế Nha Khoa Fengdan QL2028I",
      brand: "Fengdan",
      price: 32000000,
      oldPrice: 37000000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/782ab061d_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/782ab061d_generated_image.png"],
      colors: ["#FFFFFF", "#1A1A1A"],
      colorNames: ["Trắng", "Đen"],
      rating: 4.5, reviews: 54,
      tag: null,
      specs: ["Tải trọng: 150kg", "Điều khiển chân", "Đèn LED tích hợp"],
      description: "Fengdan QL2028I là lựa chọn kinh tế tốt nhất cho phòng khám mới khai trương, đảm bảo chất lượng với mức giá phù hợp.",
      inStock: true,
    },
  
    // --- ĐÈN TRÁM ---
    {
      id: "den-valo-grand",
      category: "den-tram",
      name: "Đèn Trám LED VALO Grand",
      brand: "Ultradent",
      price: 12500000,
      oldPrice: 15000000,
      image: "/images/cutouts/den-valo-grand.png",
      images: [
        "/images/cutouts/den-valo-grand.png",
        "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/d45064817_generated_image.png",
      ],
      colors: ["#FFFFFF", "#1A1A1A", "#E21F26"],
      colorNames: ["Trắng", "Đen", "Đỏ"],
      rating: 4.9, reviews: 214,
<<<<<<< HEAD
      tag: "Bán chạy",
=======
      tag: "Best Seller",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Cường độ: 1000 mW/cm²", "Bước sóng: 395-480nm", "Thời gian trùng hợp: 3-5s", "Pin sạc Li-Ion", "Màn hình LCD"],
      description: "VALO Grand là đèn trám composite cao cấp nhất của Ultradent, với cường độ ánh sáng mạnh mẽ 1000 mW/cm², giúp trùng hợp composite nhanh và triệt để. Thiết kế dạng bút mỏng nhẹ, thao tác thuận tiện trong mọi vị trí.",
      inStock: true,
    },
    {
      id: "den-ledex",
      category: "den-tram",
      name: "Đèn Trám Thẩm Mỹ LEDEX",
      brand: "LEDEX",
      price: 3500000,
      oldPrice: 4200000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/d45064817_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/d45064817_generated_image.png"],
      colors: ["#FFFFFF", "#4A90D9"],
      colorNames: ["Trắng", "Xanh"],
      rating: 4.5, reviews: 97,
<<<<<<< HEAD
      tag: "Giảm giá",
=======
      tag: "Sale",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Cường độ: 800 mW/cm²", "Bước sóng: 430-480nm", "Thời gian trùng hợp: 10s", "Pin sạc"],
      description: "LEDEX là đèn trám LED phổ biến, giá thành hợp lý, hiệu quả tốt cho các loại composite thông dụng. Thích hợp cho phòng khám mới khai trương.",
      inStock: true,
    },
    {
      id: "den-maxcure9",
      category: "den-tram",
      name: "Đèn Trám Thẩm Mỹ Maxcure 9",
      brand: "Maxcure",
      price: 5800000,
      oldPrice: null,
      image: "/images/cutouts/den-valo-grand.png",
      images: ["/images/cutouts/den-valo-grand.png"],
      colors: ["#FFFFFF", "#1A1A1A"],
      colorNames: ["Trắng", "Đen"],
      rating: 4.7, reviews: 68,
      tag: "Mới",
      specs: ["9 LED đa bước sóng", "Cường độ: 1200 mW/cm²", "5 chế độ chiếu", "Màn hình OLED"],
      description: "Maxcure 9 với 9 đầu LED đa bước sóng, tương thích với tất cả các loại composite và vật liệu quang trùng hợp hiện có. Màn hình OLED hiển thị cường độ và thời gian.",
      inStock: true,
    },
    {
      id: "den-beyond-ii",
      category: "den-tram",
      name: "Đèn Tẩy Trắng Beyond II",
      brand: "Beyond",
      price: 28000000,
      oldPrice: 34000000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/1e0976c73_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/1e0976c73_generated_image.png"],
      colors: ["#FFFFFF"],
      colorNames: ["Trắng"],
      rating: 4.8, reviews: 53,
<<<<<<< HEAD
      tag: "Nổi bật",
=======
      tag: "Hot",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Công suất: 40W", "Bước sóng: 480-520nm", "Thời gian điều trị: 30 phút", "Hệ thống làm mát", "Màn hình cảm ứng"],
      description: "Beyond II là hệ thống tẩy trắng tại phòng khám chuyên nghiệp, được tin dùng bởi hàng nghìn phòng khám thẩm mỹ trên thế giới. Hiệu quả tẩy trắng lên đến 8-10 sắc độ sau một lần điều trị.",
      inStock: true,
    },
    {
      id: "den-maxcure3",
      category: "den-tram",
      name: "Đèn Trám Thẩm Mỹ Maxcure 3",
      brand: "Maxcure",
      price: 3200000,
      oldPrice: 3800000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/d45064817_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/d45064817_generated_image.png"],
      colors: ["#FFFFFF", "#E21F26"],
      colorNames: ["Trắng", "Đỏ"],
      rating: 4.4, reviews: 42,
      tag: null,
      specs: ["3 LED đơn bước sóng", "Cường độ: 600 mW/cm²", "Pin sạc", "Nhỏ gọn"],
      description: "Maxcure 3 phiên bản mini, nhỏ gọn và tiện lợi. Lý tưởng cho phòng khám lưu động hoặc làm backup cho đèn chính.",
      inStock: true,
    },
  
    // --- CHẨN ĐOÁN HÌNH ẢNH ---
    {
      id: "xray-pax-i3d",
      category: "chan-doan",
      name: "Máy X-Quang Toàn Cảnh VATECH PaX-i3D",
      brand: "VATECH",
      price: 320000000,
      oldPrice: 380000000,
      image: "/images/cutouts/xray-pax-i3d.png",
      images: [
        "/images/cutouts/xray-pax-i3d.png",
        "/images/cutouts/xray-cbct-cs9300.png",
      ],
      colors: ["#FFFFFF", "#C0C0C0"],
      colorNames: ["Trắng", "Bạc"],
      rating: 4.9, reviews: 34,
<<<<<<< HEAD
      tag: "Bán chạy",
=======
      tag: "Best Seller",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["FOV: 5x5 đến 12x9 cm", "Độ phân giải: 200 μm voxel", "Thời gian chụp: 9-24s", "CBCT + Panoramic + Cephalometric", "Phần mềm EzDent-i"],
      description: "VATECH PaX-i3D là hệ thống CBCT 3 trong 1 tiên tiến, cho phép chụp toàn cảnh, đầu mặt và CBCT 3D trong một thiết bị duy nhất. Chất lượng hình ảnh vượt trội với công nghệ FPD detector.",
      inStock: true,
    },
    {
      id: "sensor-rvg",
      category: "chan-doan",
      name: "Cảm Biến X-Quang Nội Nha RVG 6200",
      brand: "Kodak",
      price: 42000000,
      oldPrice: null,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/f4a07e056_generated_image.png",
      images: [
        "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/f4a07e056_generated_image.png",
      ],
      colors: ["#1A1A1A", "#FFFFFF"],
      colorNames: ["Đen", "Trắng"],
      rating: 4.7, reviews: 67,
      tag: "Mới",
      specs: ["Độ phân giải: 20 lp/mm", "Kích thước sensor: Size 1 & 2", "Kết nối USB 2.0", "Lớp phủ silicon dày 5mm", "Tốc độ hình: <0.2s"],
      description: "RVG 6200 là cảm biến X-quang nội nha kỹ thuật số tốc độ cao, cho hình ảnh rõ nét tức thì. Lớp silicon bảo vệ dày, chịu được khử trùng ngâm. Tương thích với mọi phần mềm RVG thông dụng.",
      inStock: true,
    },
    {
      id: "xray-panoramic-op300",
      category: "chan-doan",
      name: "Máy X-Quang Toàn Cảnh Planmeca OP300",
      brand: "Planmeca",
      price: 180000000,
      oldPrice: 210000000,
      image: "/images/cutouts/xray-pax-i3d.png",
      images: ["/images/cutouts/xray-pax-i3d.png"],
      colors: ["#FFFFFF"],
      colorNames: ["Trắng"],
      rating: 4.8, reviews: 29,
<<<<<<< HEAD
      tag: "Cao cấp",
=======
      tag: "Premium",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Panoramic + Cephalometric", "Detector CCD cao cấp", "3 chương trình mặc định", "Kết nối Romexis", "Liều tia thấp Ultra-Low Dose"],
      description: "Planmeca OP300 là máy chụp toàn cảnh và đầu mặt kỹ thuật số, nổi tiếng với chất lượng hình ảnh xuất sắc và liều tia X thấp nhất trong phân khúc. Thương hiệu Phần Lan uy tín toàn cầu.",
      inStock: true,
    },
    {
      id: "sensor-rvg-woodpecker",
      category: "chan-doan",
      name: "Cảm Biến X-Quang Woodpecker RVG",
      brand: "Woodpecker",
      price: 18000000,
      oldPrice: 22000000,
      image: "https://media.base44.com/images/public/69cff7a985a4c7940dcab568/f4a07e056_generated_image.png",
      images: ["https://media.base44.com/images/public/69cff7a985a4c7940dcab568/f4a07e056_generated_image.png"],
      colors: ["#1A1A1A"],
      colorNames: ["Đen"],
      rating: 4.5, reviews: 88,
<<<<<<< HEAD
      tag: "Giảm giá",
=======
      tag: "Sale",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["Kết nối USB", "Size 1 & 2", "Phần mềm tặng kèm", "Bảo hành 2 năm"],
      description: "Woodpecker RVG là lựa chọn phổ biến nhất trong phân khúc cảm biến RVG giá vừa, chất lượng tốt. Phù hợp cho phòng khám muốn số hóa hệ thống X-quang với chi phí hợp lý.",
      inStock: true,
    },
    {
      id: "xray-cbct-cs9300",
      category: "chan-doan",
      name: "Hệ Thống CBCT Kodak CS 9300",
      brand: "Kodak",
      price: 450000000,
      oldPrice: null,
      image: "/images/cutouts/xray-cbct-cs9300.png",
      images: ["/images/cutouts/xray-cbct-cs9300.png"],
      colors: ["#FFFFFF", "#C0C0C0"],
      colorNames: ["Trắng", "Bạc"],
      rating: 5.0, reviews: 18,
<<<<<<< HEAD
      tag: "Cao cấp",
=======
      tag: "Premium",
>>>>>>> 815a6b25c30d0ce2b8a9d66a6dc5f1bb389afc2c
      specs: ["CBCT 3D + Panoramic + Cephalometric", "Voxel: 90 μm", "FOV: 5x5 đến 17x13 cm", "Phần mềm CS 3D Imaging", "Chứng nhận FDA & CE"],
      description: "Kodak CS 9300 là hệ thống chẩn đoán hình ảnh toàn diện nhất dành cho các trung tâm nha khoa chuyên sâu. Hình ảnh CBCT 3D chất lượng cao với liều phóng xạ thấp, hỗ trợ đầy đủ workflow implant và phẫu thuật.",
      inStock: true,
    },
  ];